# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
#from git import refresh
import pandas as pd

#Importa Tabela Config
from PyQt5.QtCore import QCoreApplication

config_df = pd.read_excel("config/config.xlsx")
df = pd.DataFrame(config_df)


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(290, 133)
        registerWindow.setMinimumSize(QtCore.QSize(290, 0))
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, -1)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lineEdit)

        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: green")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.errorLabel)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButton)

        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("closeButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.closeButton)

        self.verticalLayout.addLayout(self.formLayout)
        registerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 290, 22))
        self.menubar.setObjectName("menubar")
        registerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerWindow)
        self.statusbar.setObjectName("statusbar")
        registerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

        #Define clique do botao
        self.pushButton.clicked.connect(self.registrar)

        self.closeButton.clicked.connect(self.closeApp)

    def closeApp(self):
        exit()

    def registrar(self):
        licenca = str(self.lineEdit.text())
        df.loc[0, 'license'] = licenca
        df.to_excel("config/config.xlsx", index=False)
        self.errorLabel.setText("Imported license. Please restart the app.")



    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "Register License"))
        self.lineEdit.setPlaceholderText(_translate("registerWindow", "Put your license"))
        self.pushButton.setText(_translate("registerWindow", "Register License"))
        self.closeButton.setText(_translate("registerWindow", "Close App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerWindow = QtWidgets.QMainWindow()
    ui = Ui_registerWindow()
    ui.setupUi(registerWindow)
    registerWindow.show()
    sys.exit(app.exec_())
